// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzqRMsgEu29kUyzwFyHDSoCEnd1mKaN2s',
    appId: '1:33349924340:web:d032364308caa6b7a6f5a1',
    messagingSenderId: '33349924340',
    projectId: 'rakta-setu',
    authDomain: 'rakta-setu.firebaseapp.com',
    storageBucket: 'rakta-setu.firebasestorage.app',
    measurementId: 'G-GYK0LWHMFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESJ-rJZPbibLoMbp9ue1vjkDWAOFHuIE',
    appId: '1:33349924340:android:17e0a50c3c24e462a6f5a1',
    messagingSenderId: '33349924340',
    projectId: 'rakta-setu',
    storageBucket: 'rakta-setu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5HXk1rUDnQjmVWzCnosE8F_llLj2Gqd0',
    appId: '1:33349924340:ios:6941a34953e888ffa6f5a1',
    messagingSenderId: '33349924340',
    projectId: 'rakta-setu',
    storageBucket: 'rakta-setu.firebasestorage.app',
    iosBundleId: 'com.projectorysolutions.raktasetu.raktaSetu',
  );
}
